blank_issues_enabled: false
contact_links:
  - name: 💬 Обсуждения и Вопросы
    url: https://github.com/GeorgeStudio96/pig-rider/discussions
    about: Общие вопросы, идеи, обсуждение (не конкретные баги)
  - name: 📚 Документация по игре
    url: https://github.com/GeorgeStudio96/pig-rider/blob/main/README.md
    about: Ознакомьтесь с документацией перед созданием issue
  - name: 📖 Гайд по тестированию
    url: https://github.com/GeorgeStudio96/pig-rider/blob/main/.github/CONTRIBUTING.md
    about: Подробная инструкция как оставлять фидбек
